"""user_table

Revision ID: 567b38e1f0d5
Revises: 439b6dc131d7
Create Date: 2024-04-24 21:57:51.711722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '567b38e1f0d5'
down_revision = '439b6dc131d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index('title')

    op.drop_table('course')
    op.drop_table('favorite')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('username')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=14), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=125), nullable=True),
    sa.Column('image_file', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('password_salt', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('gender', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('birth_date', mysql.DATETIME(), nullable=False),
    sa.Column('user_role', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('last_login', mysql.DATETIME(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'phone_number'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('favorite',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('text', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('course',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('icon', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index('title', ['title'], unique=True)

    op.create_table('lesson',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('date_posted', mysql.DATETIME(), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('thumbnail', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('video', sa.BLOB(), nullable=True),
    sa.Column('documentation', sa.BLOB(), nullable=True),
    sa.Column('duration', mysql.DATETIME(), nullable=True),
    sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='lesson_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
